apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  storageClassName: localstorage
  capacity: 
    storage: 4Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: /tmp/mongodb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-hp
  namespace: lab3
spec:
  storageClassName: localstorage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce