apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
# AWS EBS storage provider
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
# Uncomment the following line if you need to bind the volume Immediately 
# volumeBindingMode: Immediate
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc 
  namespace: lab3
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi 