apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: guestbook
  labels:
    owner: Rodel_Agbing
    desc: clo835-assignment3
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend