apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc 
  namespace: lab3
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi 