apiVersion: v1
kind: Namespace
metadata:
  name: lab3-bonus
  labels:
    owner: Rodel_Agbing
    desc: clo835-assignment3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-configmap
  namespace: lab3-bonus
data:
  APP_COLOR: "red"
---
apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
  namespace: lab3-bonus
type: Opaque
data:
  # APP_COLOR = green / Base64 (https://www.base64encode.org/)
  APP_COLOR: "Ymx1ZQ=="
---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-env-from-configmap
  namespace: lab3-bonus
  labels: 
    owner: Rodel_Agbing
    desc: clo835-assignment3
    app: webapp
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    env:
    - name: APP_COLOR
      valueFrom: 
        configMapKeyRef:
          name: webapp-configmap
          key: APP_COLOR
    name: webapp-configmap-netw
    ports:
    - containerPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-env-from-secret
  namespace: lab3-bonus
  labels: 
    owner: Rodel_Agbing
    desc: clo835-assignment3
    app: webapp
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    env:
    - name: APP_COLOR
      valueFrom: 
        secretKeyRef:
          name: webapp-secret
          key: APP_COLOR
    name: webapp-secret-netw
    ports:
    - containerPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-color-plaintext
  namespace: lab3-bonus
  labels: 
    owner: Rodel_Agbing
    desc: clo835-assignment3
    app: webapp
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    env:
    - name: APP_COLOR
      value: "pink"
    name: webapp-plaintext-netw
    ports:
    - containerPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc-configmap
  namespace: lab3-bonus
  labels:
    owner: Rodel_Agbing
    desc: clo835-assignment3
    app: webapp-svc
spec:
  # No define NodePort to avoid future port conflict  
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: webapp
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc-secret
  namespace: lab3-bonus
  labels:
    owner: Rodel_Agbing
    desc: clo835-assignment3
    app: webapp-svc
spec:
  # No define NodePort to avoid future port conflict  
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: webapp